# Generated by Django 3.2.18 on 2023-05-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tavarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('narxi', models.CharField(max_length=200)),
                ('rasmi', models.FileField(upload_to='media')),
            ],
        ),
    ]
